### ISSUE TITLE
4.2.8 error 

### ISSUE THREAD

**Issue by drawnwren** [zilliztech/milvus-helm#121]
```
milvus	4.2.8   	False    	False	Helm install failed for release milvus/milvus-milvus with chart milvus@4.2.8: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:	
      	        	         	     	  line 48: mapping key "httpNumThreads" already defined at line 36 
```

With the following helmrelease:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus
  namespace: milvus
spec:
  targetNamespace: milvus
  interval: 1m
  dependsOn:
    - name: karpenter
      namespace: kube-system
  chart:
    spec:
      chart: milvus
      sourceRef:
        kind: HelmRepository
        name: milvus
        namespace: milvus
      interval: 1m
  values:
    nodeSelector:
      xoul.ai/grouping: milvus
    cluster:
      enabled: true
    serviceAccount:
      create: true
      name: milvus-s3-access-sa
      annotations: 
        eks.amazonaws.com/role-arn: "arn:aws:iam::no:role/milvus-s3-access-sa"
    service:
      type: LoadBalancer
      port: 19530
      annotations: 
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-name: milvus-service
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    pulsar:
      enabled: true
    kafka:
      enabled: false
    attu:
      enabled: true
      ingress:
        enabled: false
    minio:
      enabled: false
    externalS3:
      enabled: true
      host: "s3.us-east-2.amazonaws.com"
      port: "443"
      useSSL: true
      bucketName: "basis-milvus-s3-bucket"
      useIAM: true
      cloudProvider: "aws"
      iamEndpoint: ""
    rootCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
      resources: 
        limits:
          cpu: 1
          memory: 2Gi
    indexCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
      resources: 
        limits:
          cpu: "0.5"
          memory: 0.5Gi
    queryCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
      resources: 
        limits:
          cpu: "0.5"
          memory: 0.5Gi
    dataCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
      resources: 
        limits:
          cpu: "0.5"
          memory: 0.5Gi
      proxy:
        enabled: true
        replicas: 2
        resources: 
          limits:
            cpu: 1
            memory: 2Gi  
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
```
