### ISSUE TITLE
Allow setting nodeSelectors and tolerations for pulsar components

### ISSUE THREAD

**Issue by aliabbasjaffri** [zilliztech/milvus-helm#124]
For nodes with custom labels and taints, there is currently no way to natively set nodeSelectors and tolerations on all the pods created by pulsar in a kubernetes cluster

**Comment by aliabbasjaffri** [comment]
This can be done by bumping up pulsar version. The current set version is [2.7.8](https://github.com/zilliztech/milvus-helm/blob/4cfe1a763a4fb974907c0aaaa90f84c11484390d/charts/milvus/requirements.yaml#L15) which [does not support tolerations](https://github.com/apache/pulsar-helm-chart/blob/a919f309c6d73342196dbaf6bf146cfda8d9e8e8/charts/pulsar/templates/bookkeeper-cluster-initialize.yaml) in the helm chart, however version [3.5.0 supports tolerations](https://github.com/apache/pulsar-helm-chart/blob/7675e4270d54ef48331fdb5523b357ba0ea760ff/charts/pulsar/templates/bookkeeper-cluster-initialize.yaml#L43).

**Comment by aliabbasjaffri** [comment]
However i'm not sure what would be the side-effects of bumping the version. 

However, version `2.7.8` was updated 3 years ago, any reason why it has not been updated?

**Comment by haorenfsa** [comment]
pulsar v3 chart doesn't support pulsar v2 image. So we're still using v2 for backward compatibility. 
https://github.com/milvus-io/milvus/issues/30812

As a walk around, You can deploy pulsar with v3 chart and then configure milvus to use that pulsar. Or you can also use milvus-operator.

**Comment by haorenfsa** [comment]
@aliabbasjaffri It will probably be in October. We are still designing a solution to introduce it without affecting compatibility。

**Comment by colinbjohnson** [comment]
@aliabbasjaffri although we would love to utilize pulsar version 3 we are using the existing milvus helm charts with pulsar and _nodeSelectors_.

```yaml
proxy:
  nodeSelector:
    kubernetes.io/arch: amd64
  replicaCount: 1
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 2048Mi
      cpu: 1
  service:
    type: ClusterIP
  ports:
    pulsar: 6650
  configData:
    PULSAR_MEM: >
      -Xms2048m -Xmx2048m
    PULSAR_GC: >
      -XX:MaxDirectMemorySize=2048m
```
