### ISSUE TITLE
Cleanup rdb_data folder in milvus

### ISSUE THREAD

**Issue by mananpreetsingh** [zilliztech/milvus-helm#136]
**Environment:**

**K8**: 1.30
**Milvus version**: v2.4.12
**Deploy Mode**: STANDALONE

**Current Behavior**
The size of the rdb_data folder keeps increasing and never cleans up auto. 

![image](https://github.com/user-attachments/assets/55364464-cf1b-400c-946a-cf8f8d3c328f)

**Issue**

It seems following config in helm chart is not being supported any more:
```
standalone:
  rocksmq:
      retentionTimeInMinutes: 60
      retentionSizeInMB: 64
      rocksmqPageSize: "2147483648" ## 2 GB
      lrucacheratio: 0.06 ## rocksdb cache memory ratio
```
Seems it used to support in helmchart version 3.*.* and in Helm chart 4.0.0 it stopped supporting. Wonder hoe can we clean up `rdb_data` folder in milvus  either via helm chart config or via cli some how?
