### ISSUE TITLE
[Doc][bug?] MixCoord HA Active standyBy configuration

### ISSUE THREAD

**Issue by Archalbc** [zilliztech/milvus-helm#14]
Hi !

We use MixCoord and wanted to enable the active standby feature.

According to this chart, you should just have do that:
```
mixCoordinator:
  replicas: 2 
  activeStandby:
    enabled: true
```

But the MixCoord pod will fail and loop with this error in its logs for each type of coord (query, index, data...):
```
[2023/09/13 08:12:21.852 +00:00] [ERROR] [sessionutil/session_util.go:451] ["retry func failed"] ["retry time"=16] [error="function CompareAndSwap error for compare is false for key: querycoord"] [stack="github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).registerService\n\t/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:451\ngithub.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Register\n\t/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:271\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).Register\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:137\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:262\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:100\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111"]
```

To fix the issue, by quickly reading the error "function CompareAndSwap error for compare is false for key: XXXX",
I did a bet that I needed to enable activeStandby even with all other coordinator disabled:
```
rootCoordinator:
  activeStandby:
    enabled: true
queryCoordinator:
  activeStandby:
    enabled: true
indexCoordinator:
  activeStandby:
    enabled: true
dataCoordinator:
  activeStandby:
    enabled: true

mixCoordinator:
  replicas: 2
  activeStandby:
    enabled: true
```

And indeed now it works \o/

I think the documentation (of the values.yml file?) need somehow to be updated.

Regards,
