### ISSUE TITLE
Allow reading credentials from secrets

### ISSUE THREAD

**Issue by artesby** [zilliztech/milvus-helm#140]
possible duplicates https://github.com/zilliztech/milvus-helm/issues/128

If i understand correctly, currently:

credentials for external S3 can only be passed explicitly in values.yaml:
```
externalS3:
  accessKey: ...
  secretKey: ...
```

credentials for external kafka can only be passed explicitly in configmap:
```
extraConfigFiles:
  user.yaml: |+
    kafka:
      saslUsername: ...
      saslPassword: ...
 ```
 
 Would be great if we could read this credentials from secrets.
