### ISSUE TITLE
Minio helm chart related issues

### ISSUE THREAD

**Issue by cftang0827** [zilliztech/milvus-helm#175]
Hi there, 
I got some issuese when I was going to install milvus standalone, but sine it's from `minio`, therefore not really sure here is the proper place to ask.

When I tried to install milvus standalone version with helm chart, I got the issue, here is my `values.yaml` setup. (For minio part)

```yaml
    minio:
        enabled: true
        mode: standalone
```

And I got an error in k8s side,

```
Pods "milvus-standalone-minio-74d96b99f9-" is forbidden: error looking up service account default/milvus-standalone-minio: serviceaccount "milvus-standalone-minio" not found:Deployment does not have minimum availability.
```

Seems like system tried to install `minio` in `default` namespace, however, I was using `milvus` namespace. And the service account had been installed into `milvus` namespace.

And I looked into the source code of the helm chart (minio part)
helm chart version: `8.0.17` 

- deployment.yaml
```yaml
apiVersion: {{ template "minio.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | trimSuffix "\n" | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | trimSuffix "\n" | indent 4 }}
{{- end }}
```

- serviceaccount.yaml
```yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: "{{ .Release.Name }}"
{{- end -}}
```

Looks like there's **NO** setup of `namespace` for `minio` in `deployment.yaml` but there's `namespace` setup in `serviceaccount.yaml`, is that normal? 

I guess maybe that's why it cannot find such service account when installing milvus in different namespace. 

Thanks.
