### ISSUE TITLE
Does the external etcd cluster support etcd certificates?

### ISSUE THREAD

**Issue by dotbalo** [zilliztech/milvus-helm#37]
I looked through some deployment documents and did not find any place to configure etcd SSL certificates. There is only a bit of configuration below. Does this support etcd cluster certificates?
````
externalEtcd:
  enabled: true
  ## the endpoints of the external etcd
  ##
  endpoints:
    - 10.0.0.9:2379
  rootPath: milvus
````

**Comment by haorenfsa** [comment]
em.. seems no for now

**Comment by ViokingTung** [comment]
related to https://github.com/milvus-io/milvus/issues/28895

**Comment by haorenfsa** [comment]
@dotbalo add configurations like below in 
```yaml
extraConfigFiles:
  user.yaml: |
    etcd: 
      ssl: 
        enabled: true
        # ...
```

reference: 
![image](https://github.com/zilliztech/milvus-helm/assets/15938850/e0ad8a6e-a79e-422f-ae86-644caadedaf1)
