### ISSUE TITLE
Cannot run Milvus in our Openshift cluster with (runsAsUser, runAsGroup, fsGroup) - How to remove them?? 

### ISSUE THREAD

**Issue by tmechineni12** [zilliztech/milvus-helm#43]
Hi Team, 

We tried to use your helm templates (https://github.com/zilliztech/milvus-helm/tree/master/charts/milvus) and tried to deploy milvus on our openshift cluster, Our openshift team or Kubernetes cluster admins won't let us specify any security context i.e(runsAsUser, runAsGroup, fsGroup, ) for pods/deployments/replicasets/statefulsets, So we should not be specifying the below.     
        **# runAsUser: 1000
        # runAsGroup: 1000
        # fsGroup: 1000** 

So I had to comment them and tried to milvus install. But it does not work

![image](https://github.com/zilliztech/milvus-helm/assets/149007765/828196b5-a121-4b7d-919a-8ca3056cca5c)

None of my pods start and I see the following errors. 

![image](https://github.com/zilliztech/milvus-helm/assets/149007765/ccc66cad-a3d5-4c1c-9c9a-ba8d8cf39a0d)

![image](https://github.com/zilliztech/milvus-helm/assets/149007765/2a075a0b-e7ce-45ab-aacd-a5e54b6a36bd)

Please assist, how to proceed further.

Thanks!
Tharun M

**Comment by wyfeng001** [comment]
I thought you used MinIO  as the local storage?  
Milvus doesn't set this securityContext.  It should be those third party Charts such as MinIO, ETCD, Pursar, etc. that sets these up, they use this to avoid root execution to make it more secure.
I found the settings in minio/values.yaml
```
## Add stateful containers to have security context, if enabled MinIO will run as this
## user and group NOTE: securityContext is only enabled if persistence.enabled=true
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
```

You could use the openshift cloud storage to store the data. Disable the MinIO and set the external bucket in your values. Can have a try
```
minio:
    enabled: false

externalS3:
    enabled: true
    host: xxxxx
    port: 443
    rootPath: xxxxx
    bucketName: xxxx
    cloudProvider: xxx
    useSSL: true
    accessKey: "xxx"
    secretKey: "xxx"
```
Or you can find the related settings of minIO.persistence in values.yaml.  Disable it and have a try.  

find more info about MinIO settings in the minio chart (https://github.com/zilliztech/milvus-helm/blob/master/charts/milvus/charts/minio-8.0.17.tgz)
