### ISSUE TITLE
couldn't connect to milvus k8s ingress via tls

### ISSUE THREAD

**Issue by hive74** [zilliztech/milvus-helm#71]
Hello,
I'm using milvus db in k8s as standalone, have tls.crt and tls.key for my ingress dns and put it in standalone-pod via secretName: milvus-tls. CA-cert is also added to standalone-pod in /etc/ssl/certs. Certs are valid. Config milvus tls:

Python 3.10.12
protobuf 3.20.0
milvus-4.1.17
grpcio-tools 1.53.0
Milvus cli version: 0.4.2
Pymilvus version: 2.3.4

extraConfigFiles:
```
  user.yaml: |
    tls:
      serverPemPath: /tmp/tls.crt
      serverKeyPath: /tmp/tls.key
    common:
      security:
        tlsMode: 1
```

Ingress by default:
```
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/listen-ports-ssl: '[19530]'
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
```
```
rules:
  - host: k8s-milvus.example.com
    http:
      paths:
      - backend:
          service:
            name: my-release-milvus
            port:
              number: 19530
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - k8s-milvus.example.com
    secretName: milvus-tls
```

I get 502 in browser and Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED. trying connect via python script like connections.connect("default", host="k8s-milvus.example.com", port="443", secure=True, server_pem_path="/home/testuser/milvus/ca.pem")

What I tried:

If disable TLS on milvus, drop ingress-line nginx.ingress.kubernetes.io/backend-protocol: GRPC and keep tls on ingress - I get 404 in browser (thats good) and CERTIFICATE_VERIFY_FAILED via script.

If connect via 80 port without milvus-tls I get Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

Tried to mix params like server_pem_path, ca_pem_path, client_pem_path and etc.

Without milvus-tls in minikube and port-forward standalone-pod - it's well connecting. Through ingress its also dont work even with simple\milvus-default ingress. Maybe its main problem.

All pods are running without errors in logs. How can I connect to milvus db via python script? How fix ssl error? I can't disable ingress tls, but can do it on milvus db, if same (Ingress TLS, Milvus noTLS) config is possible.

**Comment by haorenfsa** [comment]
if you use tlsMode 1 for milvus, the annotation `nginx.ingress.kubernetes.io/backend-protocol: GRPC` value for ingress should be `GRPCS`

see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol for more information.

**Comment by haorenfsa** [comment]
Or you can also leave `nginx.ingress.kubernetes.io/backend-protocol: GRPC`, and set tlsMode to 0 for milvus.
In this way, the traffic from nginx to milvus will be Plain text GRPC.

**Comment by hive74** [comment]
Now I try noTLS config:
Values.yaml
```
extraConfigFiles:
  user.yaml: |
   tls:
     serverPemPath: /milvus/configs/cert/server.pem
     serverKeyPath: /milvus/configs/cert/server.key
   common:
     security:
       tlsMode: 0
```
Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-release-milvus
  labels:
    helm.sh/chart: milvus-4.1.17
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/version: "2.3.8"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
spec:
  defaultBackend:
    service:
      name: my-release-milvus
      port:
        number: 19530
  rules:
  - host: milvus.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-release-milvus
              port:
                number: 19530

```
I get 404 in browser and 
```
curl http://milvus.example.com:80
404 page not found
```
But in VSC when running script 
`connections.connect("default", uri="http://milvus.example.com:80", user='root', password='Milvus')` 
I get 
```
Traceback (most recent call last):
  File "/home/volodinyk/milvus/createuser.py", line 20, in <module>
    connections.connect("default", uri="http://milvus.example.com:80", user='root', password='Milvus')
  File "/home/volodinyk/.local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 356, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/volodinyk/.local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 302, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/volodinyk/.local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 136, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on milvus.example.com:80. Timeout)>
```

Only way when script works, I make port-forward from service and connection is well
`kubectl port-forward service/my-release-milvus -n milvus 27017:19530`

**Comment by haorenfsa** [comment]
The annotation `nginx.ingress.kubernetes.io/backend-protocol: GRPC` is necessary.

**Comment by hive74** [comment]
> The annotation `nginx.ingress.kubernetes.io/backend-protocol: GRPC` is necessary.

I added it to my notls config (previous message), then I get 502 in browser and curl
```
via script also `(code=2, message=Fail connecting to server on milvus.example.com:80. Timeout)>`

**Comment by haorenfsa** [comment]
em, I'm gonna need more information to be sure what's going on. Could you try use command `curl -v https://milvus.example.com:443`  and paste the output here?

**Comment by haorenfsa** [comment]
Oh, I know what's going on.

You're using the private certificate signed by yourself. So you need to add the `server.pem` when connecting.

Try this:
`connections.connect("default", host="k8s-milvus.example.com", port="443", secure=True, server_pem_path="/home/testuser/milvus/cert/server.pem")`

**Comment by hive74** [comment]
> em, I'm gonna need more information to be sure what's going on. Could you try use command `curl -v https://milvus.example.com:443` and paste the output here?

different tries
https://pastebin.com/XH8ab2fX


> Oh, I know what's going on.
> 
> You're using the private certificate signed by yourself. So you need to add the `server.pem` when connecting.
> 
> Try this: `connections.connect("default", host="k8s-milvus.example.com", port="443", secure=True, server_pem_path="/home/testuser/milvus/cert/server.pem")`

`connections.connect("default", host="milvus.example.com", port="443", secure=True, server_pem_path="/home/testuser/milvus/cert/server.pem")`
```
Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED. 
(code=2, message=Fail connecting to server on milvus.example.com:443. Timeout)>
```


Want to note, that ingress tls certs are generated by gen.sh and i try connect with them *.pem. But in user.yaml using defaults certs generating by milvus before start and tlsMode: 0, can it affect? may be need any certs?
```
extraConfigFiles:
  user.yaml: |
   tls:
     serverPemPath: /milvus/configs/cert/server.pem
     serverKeyPath: /milvus/configs/cert/server.key
   common:
     security:
       tlsMode: 0
```
