### ISSUE TITLE
我给milvus配置了gpu，为什么他没有使用呢？

### ISSUE THREAD

**Issue by luli817** [zilliztech/milvus-helm#80]
<img width="1178" alt="image" src="https://github.com/zilliztech/milvus-helm/assets/31745402/94678242-cc79-4033-a98b-3566b0b7ac4c">
![image](https://github.com/zilliztech/milvus-helm/assets/31745402/8b8fa996-5f23-4a83-a254-2bee848085b9)

**Comment by haorenfsa** [comment]
Hi @luli817: I assume you're following https://milvus.io/docs/install_standalone-helm-gpu.md#Install-Milvus-Standalone-with-GPU-Support.  You would also need to use Milvus' gpu image, which is not mentioned in this doc. 

```
image:
  all:
    repository: milvusdb/milvus
    tag: v2.3.12-gpu
```

We will update the doc soon. Thank you for your feedback!

**Comment by luli817** [comment]
好的，谢谢您，我试试，我顺便说一下，你们values里面好像没法指定runtimeclass.我需要手动修改deoloyment

**Comment by haorenfsa** [comment]
@luli817 thank you again, it's true that runtimeclass is not supported yet. By the way,  would you like to make a patch to support it?

**Comment by haorenfsa** [comment]
I'll translate the words to english for more users to follow.

**Comment by luli817** [comment]
Adding a patch to set up runtimeclass is actually quite simple, but I don't have experience in collaborative development on GitHub and am not familiar with the process. I would like to add you on WeChat and ask for your advice. Then I would like to explain why I need to add the runtimeclass parameter, because my CNI is Cilium, but Cilium cannot start in NVIDIA runtime, which means I have to configure two runtimes on this node.

**Comment by luli817** [comment]
![image](https://github.com/zilliztech/milvus-helm/assets/31745402/a14ef2af-77c1-4c7a-acbb-a29432581dd3)
![image](https://github.com/zilliztech/milvus-helm/assets/31745402/63c77809-0b50-4324-ada8-dc3e533a9ae9)

@haorenfsa hi,I have set up the GPU image, but he hasn't used GPC yet.

**Comment by haorenfsa** [comment]
@LoveEachDay @liliu-z Any idea about this?

**Comment by liliu-z** [comment]
Can I have the script you create the GPU index?

**Comment by luli817** [comment]
@liliu-z  I didn't specifically create a GPU index.

**Comment by liliu-z** [comment]
> @liliu-z I didn't specifically create a GPU index.

Then you need to do so, Plz check MIlvus' [doc](https://milvus.io/docs/gpu_index.md)

**Comment by luli817** [comment]
@liliu-z I need to create a GPU index first before Milvus can use the GPU, right?

**Comment by haorenfsa** [comment]
@luli817 I guess yes. does it work?

**Comment by bmkor** [comment]
Would like to chip in. We tried to add the `runtimeClassName: ''` in the templates for both indexnode and querynode. Afterwards, we specified the value 'nvidia' as below:

```
image:
  all:
    repository: milvusdb/milvus
    tag: v2.5.4-gpu
    pullPolicy: IfNotPresent
indexNode:
  runtimeClassName: "nvidia"
  resources:
    requests:
      nvidia.com/gpu: "1"
    limits:
      nvidia.com/gpu: "1"
queryNode:
  runtimeClassName: "nvidia"
  resources:
    requests:
      nvidia.com/gpu: "1"
    limits:
      nvidia.com/gpu: "1"
```

Inspecting the relevant worker nodes save the gpu memory occupied as expected.

<img width="1144" alt="Image" src="https://github.com/user-attachments/assets/a51423e3-4acb-44a2-abe2-b2a248465f7a" />

Wondering
1. the image v.2.5.4-gpu not only for indexNode and queryNode but for others. So, would it be better to specify this image for these two nodes or it doesn't matter?
2. could we submit a pull request for the modified templates?
