### ISSUE TITLE
How does Milvus install by Helm can support dynamic configuration changes when I changed config user.yaml in config map?

### ISSUE THREAD

**Issue by anhnch30820** [zilliztech/milvus-helm#94]
I see document in K8s
A container using a ConfigMap as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes#using-subpath) volume mount will not receive ConfigMap updates.
And helm use subPath:
```
- name: milvus-config
  mountPath: /milvus/configs/user.yaml
  subPath: user.yaml
  readOnly: true
```

**Comment by haorenfsa** [comment]
@anhnch30820 For now it's supported in milvus-operator , we'll migrate it to helm soon.

https://github.com/zilliztech/milvus-operator/releases/tag/v0.9.15

**Comment by anhnch30820** [comment]
Hi @haorenfsa, Does helm support dynamic for now?

**Comment by haorenfsa** [comment]
@anhnch30820 No, I haven't got time to manage that. l list the changes needed below., so that you may change your deployment for dynamic config. Or if you're interested, you could also make a patch for our chart.

Each deploy should be added with:
- an starting script `/milvus/tools/run.sh` and related volumeMounts.
- an `initContainer` to copy binaries needed for `run.sh`
- change the volumeMount's path, and remove subpath field.



```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-indexnode
spec:
  template:
    spec:
      containers:
      - args:
        - /milvus/tools/run.sh
        - milvus
        - run
        - indexnode
        name: indexnode
        volumeMounts:
        - mountPath: /milvus/configs/operator
          name: milvus-config
          readOnly: true
        - mountPath: /milvus/tools
          name: tools
      initContainers:
      - args:
        - /init.sh
        command:
        - /bin/sh
        image: milvusdb/milvus-tools:v1.0.0
        resources: {}
        volumeMounts:
        - mountPath: /milvus/configs/operator
          name: milvus-config
          readOnly: true
        - mountPath: /milvus/tools
          name: tools
      volumes:
      - configMap:
          name: milvus
        name: milvus-config
      - emptyDir: {}
        name: tools
```
